name: updating proxy

on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - name: start proxy scraper
        run: |
          cd .github/workflows
          npm ci
          node index.js
      - name: start commit
        run: |
          git config --local user.name "bot"
          git status
          echo -e "- jumlah proxy: $(cat proxies.csv | wc -l)\n- terakhir diupdate: $(date +'%Y-%m-%d %T')" > readme.md
          git add proxies.csv readme.md
          git commit -m "update: write $(cat proxies.csv | wc -l) proxies"
      - name: push changes
        uses: ad-m/github-push-action@master
        with: 
         github_token: ${{ secrets.TOKEN }}
         force: true
