name: updating proxy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - name: updating proxies.txt
        run: |
          node -v > readme.md
      - name: start commit
        run: |
          git config --local user.name "bot"
          git status
          git add .
          git commit -m "update: ..."
      - name: push changes
        uses: ad-m/github-push-action@master
        with: 
         github_token: ${{ secrets.TOKEN }}
         force: true
