name: Proxy Updater

on:
  schedule:
    - cron: "* * * * *"

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - name: start proxy scraper
        run: |
          cd .github/workflows
          npm ci
          node index.js
      - name: generate README.md
        run: |
          echo -e "# Overview" > README.md
          echo -e "  - **jumlah proxy:** ±$(cat *.txt | wc -l)" >> README.md
          echo -e "  - **terakhir diupdate:** $(date +'%Y-%m-%d %T')\n" >> README.md

          echo -e "# Download" >> README.md
          for file in *.txt;
          do
            echo "  - **for $(echo $file | cut -d'_' -f1 | tr 'a-z' 'A-Z')**<br/>" >> README.md
            echo "    `curl https://raw.githubusercontent.com/zevtyardt/proxy-list/main/$file -O $file`" >> README.md
          done

      - name: start commit
        run: |
          git config --local user.name ${{ secrets.name }}
          git status
          git add *.txt README.md csv/
          git commit -m "update: write $(cat *.txt | wc -l) proxies"
      - name: push changes
        uses: ad-m/github-push-action@master
        with: 
         github_token: ${{ secrets.TOKEN }}
         force: true
